name: Build and Release EXE

on:
  push:
    tags:
      - 'v*.*.*'
    paths:
      - 'src/MakingMcp/MakingMcp.csproj'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 10.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore src/MakingMcp/MakingMcp.csproj

      - name: Build Release
        run: dotnet build src/MakingMcp/MakingMcp.csproj --configuration Release --no-restore

      - name: Publish EXE
        run: dotnet publish src/MakingMcp/MakingMcp.csproj --configuration Release --runtime win-x64 --self-contained true --output publish

      - name: Get tag name
        id: get_tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "TAG=${{ github.event.inputs.version }}" >> $GITHUB_ENV
            echo "IS_TAG=true" >> $GITHUB_ENV
            echo "IS_MANUAL=true" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
            echo "IS_TAG=true" >> $GITHUB_ENV
            echo "IS_MANUAL=false" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
            echo "IS_TAG=false" >> $GITHUB_ENV
            echo "IS_MANUAL=false" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Create tag for manual release
        if: env.IS_MANUAL == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "${{ env.TAG }}" -m "Release ${{ env.TAG }}"
          git push origin "${{ env.TAG }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release with Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          files: publish/MakingMcp.exe
          prerelease: ${{ env.IS_TAG == 'false' }}
          make_latest: ${{ env.IS_TAG == 'false' }}
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
