name: Build and Release EXE

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 10.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore src/MakingMcp/MakingMcp.csproj

      - name: Build Release
        run: dotnet build src/MakingMcp/MakingMcp.csproj --configuration Release --no-restore

      - name: Publish EXE
        run: dotnet publish src/MakingMcp/MakingMcp.csproj --configuration Release --runtime win-x64 --self-contained true --output publish

      - name: Get tag name
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v2
        with:
          files: publish/MakingMcp.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

